apiVersion: v1
kind: Secret
metadata:
  name: platamx-secrets
type: Opaque
data:
  # These are example values - in a real environment, use proper secrets management
  # Values are base64 encoded
  jwt-secret: eW91ci1zZWNyZXQta2V5
  mongo-auth-uri: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvcGxhdGFteC1hdXRo
  mongo-catalog-uri: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvcGxhdGFteC1jYXRhbG9n
  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXM=
  postgres-payments-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvcGxhdGFteF9wYXltZW50cw==
  postgres-shipping-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvcGxhdGFteF9zaGlwcGluZw==
  postgres-notifications-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvcGxhdGFteF9ub3RpZmljYXRpb25z
  redis-url: cmVkaXM6Ly9yZWRpczo2Mzc5
  elasticsearch-url: aHR0cDovL2VsYXN0aWNzZWFyY2g6OTIwMA==
  stripe-secret-key: eW91ci1zdHJpcGUta2V5
  smtp-host: c210cC5leGFtcGxlLmNvbQ==
  smtp-port: NTg3
  smtp-user: c210cC11c2Vy
  smtp-pass: c210cC1wYXNzd29yZA==
  firebase-service-account: e30=